spring.application.name=tool
# Enables the web interface to view your DB
spring.h2.console.enabled=true
# The URL to access the console (localhost:8080/h2-console)
spring.h2.console.path=/h2-console
# Keeps the data in a file so it doesn't disappear when you restart
spring.datasource.url=jdbc:h2:file:./data/analyticsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev